--------------------------------------------------------
--  File created - Tuesday-March-31-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AGENCIA
--------------------------------------------------------

  CREATE TABLE "CRUDAUTOS"."AGENCIA" 
   (	"IDAGENCIA" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"DIRECCION" VARCHAR2(200 BYTE), 
	"TELEFONO" VARCHAR2(12 BYTE), 
	"CIUDAD" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AUTOS
--------------------------------------------------------

  CREATE TABLE "CRUDAUTOS"."AUTOS" 
   (	"IDAUTO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"MARCA" VARCHAR2(50 BYTE), 
	"MODELO" VARCHAR2(50 BYTE), 
	"ANIO" VARCHAR2(4 BYTE), 
	"COLOR" VARCHAR2(30 BYTE), 
	"PRECIO" NUMBER(12,2), 
	"PLACA" VARCHAR2(20 BYTE), 
	"IDAGENCIAS" NUMBER(20,0), 
	"IMAGEN" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("IMAGEN") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into CRUDAUTOS.AGENCIA
SET DEFINE OFF;
Insert into CRUDAUTOS.AGENCIA (IDAGENCIA,NOMBRE,DIRECCION,TELEFONO,CIUDAD) values (22,'Agencia Central','Av.Insurgentes Sur 1000 CDMX','5551234567','Ciudad de Mexico');
Insert into CRUDAUTOS.AGENCIA (IDAGENCIA,NOMBRE,DIRECCION,TELEFONO,CIUDAD) values (23,'Autos del Norte','Blvd. Diaz Ordaz 500, Monterry','8187654321','Monterrey');
Insert into CRUDAUTOS.AGENCIA (IDAGENCIA,NOMBRE,DIRECCION,TELEFONO,CIUDAD) values (24,'Distribuidora Occidente','Av. Vallarta 300','5512456874','Guadalajara');
Insert into CRUDAUTOS.AGENCIA (IDAGENCIA,NOMBRE,DIRECCION,TELEFONO,CIUDAD) values (25,'Agencia Sureste','Av Colon 75 Merida','9991239876','Merida');
REM INSERTING into CRUDAUTOS.AUTOS
SET DEFINE OFF;
Insert into CRUDAUTOS.AUTOS (IDAUTO,MARCA,MODELO,ANIO,COLOR,PRECIO,PLACA,IDAGENCIAS) values (43,'Nissan','Sentra','2018','Blanco',5200000,'QSA988',22);
Insert into CRUDAUTOS.AUTOS (IDAUTO,MARCA,MODELO,ANIO,COLOR,PRECIO,PLACA,IDAGENCIAS) values (41,'Honda','Civic','2019','Negro',270000,'XYZ789',23);
Insert into CRUDAUTOS.AUTOS (IDAUTO,MARCA,MODELO,ANIO,COLOR,PRECIO,PLACA,IDAGENCIAS) values (42,'Ford','Focus','2021','Azul',2700000,'LMN456',22);
Insert into CRUDAUTOS.AUTOS (IDAUTO,MARCA,MODELO,ANIO,COLOR,PRECIO,PLACA,IDAGENCIAS) values (44,'Chevrolet','Aveo','2022','Gris',220000,'QRS987',25);
Insert into CRUDAUTOS.AUTOS (IDAUTO,MARCA,MODELO,ANIO,COLOR,PRECIO,PLACA,IDAGENCIAS) values (45,'Toyota','Corolla','2024','Rojo',320000,'ACV125',23);
Insert into CRUDAUTOS.AUTOS (IDAUTO,MARCA,MODELO,ANIO,COLOR,PRECIO,PLACA,IDAGENCIAS) values (46,'Toyota','Corolla','2013','Negro',32555000,'ACVS528',23);
Insert into CRUDAUTOS.AUTOS (IDAUTO,MARCA,MODELO,ANIO,COLOR,PRECIO,PLACA,IDAGENCIAS) values (47,'Mazda','3','2021','Rojo',280000,'JKL234',25);
Insert into CRUDAUTOS.AUTOS (IDAUTO,MARCA,MODELO,ANIO,COLOR,PRECIO,PLACA,IDAGENCIAS) values (48,'Volkswagen','Jetta','2020','Gris',260000,'VWX567',24);
Insert into CRUDAUTOS.AUTOS (IDAUTO,MARCA,MODELO,ANIO,COLOR,PRECIO,PLACA,IDAGENCIAS) values (49,'Hyundai','Elantra','2019','Azul',240000,'HYD890',25);
Insert into CRUDAUTOS.AUTOS (IDAUTO,MARCA,MODELO,ANIO,COLOR,PRECIO,PLACA,IDAGENCIAS) values (50,'Kia','Rio','2022','Negro',210000,'KIA321',23);
Insert into CRUDAUTOS.AUTOS (IDAUTO,MARCA,MODELO,ANIO,COLOR,PRECIO,PLACA,IDAGENCIAS) values (51,'BMW','Serie 3','2021','Blanco',5500000,'BMW654',22);
Insert into CRUDAUTOS.AUTOS (IDAUTO,MARCA,MODELO,ANIO,COLOR,PRECIO,PLACA,IDAGENCIAS) values (52,'Renault','Kardian','2018','Naranja',1800000,'KAR1256',22);
Insert into CRUDAUTOS.AUTOS (IDAUTO,MARCA,MODELO,ANIO,COLOR,PRECIO,PLACA,IDAGENCIAS) values (53,'Mercedes-Benz','C200','2022','Negro',6500000,'MBZ987',24);
Insert into CRUDAUTOS.AUTOS (IDAUTO,MARCA,MODELO,ANIO,COLOR,PRECIO,PLACA,IDAGENCIAS) values (54,'Audi','A4','2020','Gris oscuro',6000000,'AUD456',23);
Insert into CRUDAUTOS.AUTOS (IDAUTO,MARCA,MODELO,ANIO,COLOR,PRECIO,PLACA,IDAGENCIAS) values (55,'Subaru ','Impreza','2021','Azul',320000,'SUB123',22);
--------------------------------------------------------
--  Constraints for Table AUTOS
--------------------------------------------------------

  ALTER TABLE "CRUDAUTOS"."AUTOS" MODIFY ("IDAUTO" NOT NULL ENABLE);
  ALTER TABLE "CRUDAUTOS"."AUTOS" MODIFY ("MARCA" NOT NULL ENABLE);
  ALTER TABLE "CRUDAUTOS"."AUTOS" MODIFY ("MODELO" NOT NULL ENABLE);
  ALTER TABLE "CRUDAUTOS"."AUTOS" MODIFY ("ANIO" NOT NULL ENABLE);
  ALTER TABLE "CRUDAUTOS"."AUTOS" ADD PRIMARY KEY ("IDAUTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AGENCIA
--------------------------------------------------------

  ALTER TABLE "CRUDAUTOS"."AGENCIA" MODIFY ("IDAGENCIA" NOT NULL ENABLE);
  ALTER TABLE "CRUDAUTOS"."AGENCIA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "CRUDAUTOS"."AGENCIA" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "CRUDAUTOS"."AGENCIA" ADD PRIMARY KEY ("IDAGENCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AUTOS
--------------------------------------------------------

  ALTER TABLE "CRUDAUTOS"."AUTOS" ADD CONSTRAINT "FK_AUTO_AGENCIA" FOREIGN KEY ("IDAGENCIAS")
	  REFERENCES "CRUDAUTOS"."AGENCIA" ("IDAGENCIA") ENABLE;
